#!/bin/bash

case $1 in
e*)
	SUB=EN
	SUBJECT=Englisch
	;;
f*)
	SUB=FR
	SUBJECT=Französisch
	;;
*)
	echo "Unknown subject: $1"
	exit 1	
	;;	
esac

echo "Subject is $SUB"
FILE=Hausaufgaben-Julie-$(date +%F)-$SUB.pdf

echo $SUBJECT Hausaufgaben - Julie 7c - Liebe Grüße | pbcopy

topdf $* &&
mv Combined.pdf $FILE &&
rm $* &&
echo Successfully written $FILE &&
open $FILE

