alias ls='ls -Gh'
alias cd='cd -P'
alias mvn='/opt/apache-maven-3.0.5/bin/mvn'
alias jcli='/opt/wildfly/bin/jboss-cli.sh --connect'
#alias jconsole='/opt/wildfly/bin/jconsole.sh service:jmx:http-remoting-jmx://localhost:9990'
#alias mongod='mongod --config /usr/local/etc/mongod.conf'
alias wf='/opt/wildfly/bin/standalone.sh'
alias ports='lsof -i -P | grep -i listen'
alias eclipse='(cd ~/Downloads/jbpm-installer; ant start.eclipse)'
alias mysql='mysql -A'
alias mysqld='(cd; nohup /usr/local/bin/mysqld & sleep 1 && tail -1 nohup.out)'
alias mysqldd='(cd; nohup /usr/local/bin/mysqld --slow-query-log --log-queries-not-using-indexes --slow-query-log-file=/tmp/mysql/slow.log --long_query_time=1  & sleep 1 && tail -1 nohup.out)'
alias logm='ssh wildfly@172.16.0.34 log | less +G'
alias logs='ssh wildfly@172.16.0.156 log | less +G'
alias kie='(cd /opt/local/wildfly; bin/standalone.sh --server-config=standalone-full.xml)'
