#!/bin/sh

setupKeyBindings() {
    mkdir -p ~/Library/KeyBindings/
    cat << EOF > ~/Library/KeyBindings/DefaultKeyBindings.dict
{
    "\UF729"  = moveToBeginningOfLine:; // home
    "\UF72B"  = moveToEndOfLine:; // end
    "$\UF729" = moveToBeginningOfLineAndModifySelection:; // shift-home
    "$\UF72B" = moveToEndOfLineAndModifySelection:; // shift-end
}
EOF
}

set -x

setupKeyBindings
